sudo: false

language: groovy

install: true

script:
  - ./gradlew :gradle-junit-reports:uploadArchives -c settings-local.gradle
  - ./gradlew :gradle-junit-reports:test -c settings-local.gradle

jdk:
  - oraclejdk8

branches:
  only:
    - master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

sudo: false